package net.designtypes.examples;

public enum SmokingHabitTestType {
	NON_SMOKER,
	STOPPED_SMOKING,
	LESS_THAN_5_CIGARETTES_PER_DAY,
	LESS_THAN_20_CIGARETTES_PER_DAY,
	MORE_THAN_20_CIGARETTES_PER_DAY;
}
